version: '3'

services:
  ahoraloapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: ahoralo-docker
    container_name: ahoraloapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      JWT_SECRET: ${JWT_SECRET}
      HOST_API: ${HOST_API}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
    # working_dir: /var/www/ahoralo
    # volumes:
    #   - ./:/var/www/ahoralo

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: ahoralodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
